vec1<- c(0,2)
vec2<- c(TRUE, FALSE)
cat("elments wise and",vec2 & vec1)
cat("elments wise or",vec2 | vec1)
cat("elments wise not",!vec2)
cat("logical and",vec2 && vec1)
cat("logical or",vec2 || vec1)
cat("logical not",!vec2)
typeof(vec1)
